# Generated by Django 4.2.10 on 2025-11-29 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='Other', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='thehackernews.com', max_length=255)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('published_date', models.CharField(blank=True, default='', max_length=100)),
                ('is_indexed', models.BooleanField(db_index=True, default=False)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('interested_topics', models.JSONField(blank=True, default=list)),
                ('interest_profile', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('pages_scraped', models.IntegerField(default=0)),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_indexed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('interest_profile', models.JSONField(blank=True, default=dict)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('notification_threshold', models.FloatField(default=0.5)),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', max_length=20)),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('confidence', models.CharField(blank=True, default='', max_length=50)),
                ('key_insights', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('expanded_query', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleInterestMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('matching_topics', models.JSONField(default=list)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_matches', to='chatbot.article')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_matches', to='chatbot.userprofile')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='chatbot_art_categor_adcc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source'], name='chatbot_art_source_cea351_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_indexed'], name='chatbot_art_is_inde_b2f91e_idx'),
        ),
        migrations.AddIndex(
            model_name='articleinterestmatch',
            index=models.Index(fields=['notification_sent', 'match_score'], name='chatbot_art_notific_792cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='articleinterestmatch',
            index=models.Index(fields=['user_profile', 'notification_sent'], name='chatbot_art_user_pr_1ab931_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articleinterestmatch',
            unique_together={('article', 'user_profile')},
        ),
    ]
