# Generated by Django 5.2.8 on 2025-11-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='interested_topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
