# Generated by Django 5.2.8 on 2025-11-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_interested_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='interest_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('interest_profile', models.JSONField(blank=True, default=dict)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('notification_threshold', models.FloatField(default=0.5)),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', max_length=20)),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleInterestMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('matching_topics', models.JSONField(default=list)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_matches', to='chatbot.article')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_matches', to='chatbot.userprofile')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['notification_sent', 'match_score'], name='chatbot_art_notific_792cf9_idx'), models.Index(fields=['user_profile', 'notification_sent'], name='chatbot_art_user_pr_1ab931_idx')],
                'unique_together': {('article', 'user_profile')},
            },
        ),
    ]
