# Generated by Django 4.2.10 on 2025-11-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_category_scores_and_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
